const checkArray = [
  "prophet",
  "muhammad",
  "muhamad",
  "jesus",
  "musa",
  "ibrahim",
  "abubakar",
  "umar",
  "usman",
  "ali",
  "hazrat",
  "hazarat",
  "rasool's companion",
  "islamic",
  "muslim",
  "islam",
  "judiasm",
  "jew",
  "catholic",
  "Pedophilia",
  "Smut",
  "Extremism",
  "Slander",
  "Vulgar",
  "Inappropriate",
  "Obscene",
  "Torture",
  "Exploitation",
  "nigga",
  "bitch",
  "gay",
  "hentai",
  "porn",
  "sex",
  "fuck",
  "murder",
  "kill",
  "harass",
  "ass",
  "butt",
  "pedo",
  "child porn",
  "incest",
  "lesbian",
  "threesome",
  "anal",
  "vagina",
  "pussy",
  "dick",
  "penis",
  "rape",
  "undressing",
  "unclothing",
  "bikini",
  "lingeries",
  "bra",
  "mini dresses",
  "thong",
  "nude",
  "naked",
  "self-harm",
  "harassments",
  "drugs",
  "Explicit nudity",
  "swastikas",
  "white supremacist ",
  "Animal cruelty",
  "abuse",
  "suicide",
  "Gore ",
  "mutilation",
  "Pornography",
  "Racism",
  "Violence",
  "Brutality",
  "Terrorism",
  "Genocide",
  "Illegal",
  "Offensive",
  "child abuse",
  " Suffering",
  "Slavery",
  "Bullying",
  "Alcoholism",
  "Substance abuse",
  "Anorexia",
  "Bulimia",
  "Obesity",
  "Mental illness",
  "Insanity",
  "Trauma",
  "Suffocation",
  "Misery",
  "asshole",
  "son of a bitch",
  "motherfucker",
  "gangster",
  "mafia",
  "gang",
  "voilence",
  "voilent",
  "killer",
  "indian",
  "pakistani",
  "american",
  "russian",
  "british",
  "german",
  "french",
  "arabic",
  "arab",
  "palestinian",
  "turkinsh",
];

export const hasAnyWord = (sentence) => {
  // Check if either sentence or checkArray is empty
  if (!sentence) return true;

  // Convert the sentence to lowercase for case-insensitive comparison
  sentence = sentence.toLowerCase();

  // Use some() method to check if any word exists in the sentence
  return checkArray.some((word) => sentence.includes(word));
};
